# Generated by Django 3.0.8 on 2020-07-23 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_orderitem_product'),
        ('shop', '0003_auto_20200723_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='shop.Produit'),
        ),
    ]
