# Generated by Django 3.0.8 on 2020-07-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200722_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('flickr', 'fa-flickr'), ('facebook', 'fa-facebook'), ('dribble', 'fa-dribbble'), ('linkedin', 'fa-linkedin-in'), ('instagram', 'fa-instagram'), ('pinterest', 'fa-pinterest'), ('google-plus', 'fa-google-plus-g'), ('rss', 'fa-rss')], max_length=20, null=True),
        ),
    ]
