# Generated by Django 3.0.8 on 2020-07-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200722_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('facebook', 'fa-facebook'), ('linkedin', 'fa-linkedin-in'), ('flickr', 'fa-flickr'), ('google-plus', 'fa-google-plus-g'), ('dribble', 'fa-dribbble'), ('instagram', 'fa-instagram'), ('rss', 'fa-rss'), ('pinterest', 'fa-pinterest')], max_length=20, null=True),
        ),
    ]
