# Generated by Django 3.0.8 on 2020-07-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200723_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('instagram', 'fa-instagram'), ('flickr', 'fa-flickr'), ('dribble', 'fa-dribbble'), ('google-plus', 'fa-google-plus-g'), ('facebook', 'fa-facebook'), ('rss', 'fa-rss'), ('pinterest', 'fa-pinterest'), ('linkedin', 'fa-linkedin-in')], max_length=20, null=True),
        ),
    ]
