# Generated by Django 3.0.8 on 2020-07-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200723_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('pinterest', 'fa-pinterest'), ('google-plus', 'fa-google-plus-g'), ('rss', 'fa-rss'), ('dribble', 'fa-dribbble'), ('flickr', 'fa-flickr'), ('facebook', 'fa-facebook'), ('linkedin', 'fa-linkedin-in'), ('instagram', 'fa-instagram')], max_length=20, null=True),
        ),
    ]
