# Generated by Django 3.0.8 on 2020-07-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200723_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('rss', 'fa-rss'), ('dribble', 'fa-dribbble'), ('linkedin', 'fa-linkedin-in'), ('instagram', 'fa-instagram'), ('google-plus', 'fa-google-plus-g'), ('flickr', 'fa-flickr'), ('facebook', 'fa-facebook'), ('pinterest', 'fa-pinterest')], max_length=20, null=True),
        ),
    ]
