# Generated by Django 3.0.8 on 2020-07-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200723_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('rss', 'fa-rss'), ('google-plus', 'fa-google-plus-g'), ('facebook', 'fa-facebook'), ('dribble', 'fa-dribbble'), ('flickr', 'fa-flickr'), ('instagram', 'fa-instagram'), ('linkedin', 'fa-linkedin-in'), ('pinterest', 'fa-pinterest')], max_length=20, null=True),
        ),
    ]
