# Generated by Django 3.0.8 on 2020-07-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200725_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('google-plus', 'fa-google-plus-g'), ('flickr', 'fa-flickr'), ('linkedin', 'fa-linkedin-in'), ('instagram', 'fa-instagram'), ('dribble', 'fa-dribbble'), ('rss', 'fa-rss'), ('facebook', 'fa-facebook'), ('pinterest', 'fa-pinterest')], max_length=20, null=True),
        ),
    ]
