# Generated by Django 3.0.8 on 2020-07-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200725_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/Team')),
                ('titre', models.CharField(max_length=255, null=True)),
                ('statu', models.CharField(max_length=255, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'verbose_name': 'Social account', 'verbose_name_plural': 'Socials account'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='website',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='presentation',
            old_name='nom',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mapurl',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='video',
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('facebook', 'fa-facebook-f'), ('instagram', 'fa-instagram'), ('twitter', 'fa fa-twitter'), ('youtube', 'fa fa-youtube-play')], max_length=20, null=True),
        ),
    ]
