# Generated by Django 3.0.8 on 2020-07-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200725_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225, null=True)),
                ('image', models.ImageField(null=True, upload_to='image/categorie')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Category product',
                'verbose_name_plural': 'Category product',
            },
        ),
        migrations.CreateModel(
            name='Feeback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225, null=True)),
                ('image', models.ImageField(upload_to='image/categorie')),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Feeback',
                'verbose_name_plural': 'Feeback',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225, null=True)),
                ('image', models.ImageField(upload_to='image/categorie')),
                ('description', models.TextField()),
                ('auteur', models.CharField(max_length=225, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=225, null=True)),
                ('image', models.ImageField(upload_to='image/categorie')),
                ('description', models.TextField()),
                ('prix', models.FloatField(null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pub',
                'verbose_name_plural': 'Pub',
            },
        ),
        migrations.CreateModel(
            name='Trouver_le_velo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, null=True)),
                ('type_velo', models.CharField(max_length=255, null=True)),
                ('taille_de_roue', models.PositiveIntegerField(null=True)),
                ('marque', models.CharField(max_length=225, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'trouver le velo',
                'verbose_name_plural': 'trouver le velo',
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='prix',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Our_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=225, null=True)),
                ('image', models.ImageField(upload_to='image/categorie')),
                ('prix1', models.FloatField(null=True)),
                ('prix2', models.FloatField(null=True)),
                ('taille_du_cadre', models.PositiveIntegerField(null=True)),
                ('nombre_de_vitesse', models.IntegerField(null=True)),
                ('classe', models.CharField(max_length=225)),
                ('pays', models.CharField(max_length=225)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('category_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Category_product')),
            ],
            options={
                'verbose_name': 'Our_products',
                'verbose_name_plural': 'Our_products',
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='categorie_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Category_product'),
        ),
    ]
