# Generated by Django 3.0.8 on 2020-07-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200725_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Present',
            new_name='Presentation',
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'presentation', 'verbose_name_plural': 'presentations'},
        ),
    ]
