# Generated by Django 3.0.8 on 2020-07-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_sliders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
