# Generated by Django 3.0.8 on 2020-07-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200726_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliders',
            old_name='prix',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='sliders',
            name='image',
            field=models.ImageField(null=True, upload_to='images/sliders'),
        ),
    ]
